import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/style.module.css'
import { Post } from '@/types'
import Header from './components/header'
import { useSession } from 'next-auth/react'

type Props = {
  posts: Post[];
};


export default function Home({ posts }: Props) {
  const { data: session } = useSession();

  console.log(posts);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header session={session} />
      <main className={styles.main}>
        <div className={styles.postCardBox}>
          {Array.isArray(posts) && posts.map((post: Post) => (
              <Link key={post.id} href={`posts/${post.id}`} className={styles.postCardLink}>
                <div className={styles.postImageBox}><img src={post.image_url || '/no-image.jpg'} alt="Post image" className={styles.postImage} /></div>
                <div className={styles.postCard}>
                    <h2 className={styles.postTitle}>{post.title}</h2>
                    <p className={styles.postDate}><i className="material-icons">schedule</i>{ new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(post.created_at))}</p>
                </div>
              </Link>
          ))}
        </div>
           
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3001/api/v1/posts");
  const posts = await res.json();

  return {
    props: {
      posts,
    },
    revalidate: 60 * 60 * 24,
  }
}